var webpack = require('webpack');
var path = require('path');
var HtmlWebpackPlugin = require('html-webpack-plugin');

const VENDOR_LIBS = [
  'faker', 'lodash', 'react', 'react-dom', 'react-input-range',
  'react-redux', 'react-router', 'redux', 'redux-form', 'redux-thunk'
];

module.exports = {
  // key value pair, name represents what you want the file name to be
  entry: {
    bundle: './src/index.js',
    vendor: VENDOR_LIBS
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].[chunkhash].js' // for cache busting, hash of file contents
  },                                  // so file name does not change if contents do not change
  module: {
    rules : [
      {
        use: 'babel-loader',
        test: /\.js$/,
        exclude: /node_modules/
      },
      {
        use: ['style-loader', 'css-loader'],
        test: /\.css$/
      }
    ]
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest']
    }), // if you find any duplicates, pull them out and add them to the vendor file
    new HtmlWebpackPlugin({
      template: 'src/index.html'
    }), // for every js file generated by webpack, automatically include in html as script tags
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
    })
  ]
};
